import React, { useCallback, useEffect, useState } from "react";
import ReactDOM from "react-dom";

/*
This code is using the use Callback hook to memoize the function The callback function
will be called when the component mounts and unmounts but not when it updates
- generated by stenography autopilot [ 🚗👩‍✈️ ]
*/

const BackTopBtn = ({ visibleHeight = 240 }) => {
  const [show, setShow] = useState(false);
  const [y, setY] = useState(window.scrollY);

  const handleScrollDirection = useCallback(
    (e) => {
      const window = e.currentTarget;
      if (window.scrollY < visibleHeight) {
        setShow(false);
        return;
      }
      if (y > window.scrollY) {
        setShow(true);
      } else if (y < window.scrollY) {
        setShow(false);
      }
      setY(window.scrollY);
    },
    [y, visibleHeight]
  );

  useEffect(() => {
    setY(window.scrollY);
    window.addEventListener("scroll", handleScrollDirection);

    return () => {
      window.removeEventListener("scroll", handleScrollDirection);
    };
  }, [handleScrollDirection]);

  return ReactDOM.createPortal(
    <button
      className={`back-top fixed flex justify-center items-center h-11 w-11 bg-white rounded-full hover:bg-gray-50 active:bg-gray-200 dark:bg-gray-700 dark:text-gray-400 dark:hover:scale-95 dark:active:bg-gray-600 z-[999] ${
        show ? "scale-100" : "scale-0"
      }`}
      onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
    >
      ↑
    </button>,
    document.body
  );
};

export default React.memo(BackTopBtn);
